title: "Nocturnum's Devblog"
author:
    name: "Nocturnum91"
description: "Nocturnum's github blog"
baseurl: ""
url: "https://nocturnum91.github.io"

encoding: "utf-8"
locale: "ko"
timezone: Asia/Seoul
#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - dev.md
 - free.md
 - tags.md
 - about.md
 # - contact.md

style: dark
# footer: 'follow us on <a href="https://twitter.com/nocturnum91">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true